In [6]:
#Элемент матрицы называется локальным минимумом, если он строго меньше всех
#имеющихся у него соседей. Подсчитать количество локальных минимумов заданной
#матрицы размером 10 на 10. Найти сумму модулей элементов, расположенных выше
#главной диагонали.

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np 

nrows = 10
ncols = 10

m = np.random.randint(25, size=(nrows, ncols))

print(m)

[[23 17  2 22  8 21 14  5 24 15]
 [22  8  3 21 19 16  8  9 12 16]
 [17 19  3 17  3 19 20 23  6 21]
 [16 12 17 17 18 16 20 10  3 17]
 [ 8  3  6 12 23  8  2 15 10 22]
 [ 8 19  8  1 14 20  4 16 19  3]
 [23 15 11 11  8 11 19 21  4 15]
 [23 21 16 12  3 11  6 15 10  1]
 [21  0  7 23  1 15 14 19 10 19]
 [18  6 24  4 20 13  2  5  2 15]]


In [9]:
count = 0
for i in range(nrows):
    for j in range(ncols):
        if i == 0 and j == 0:
            if m[i][j] <= m[i][j+1] and  m[i][j] <= m[i+1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif i == 0 and j == nrows-1:
            if m[i][j] <= m[i][j-1] and  m[i][j] <= m[i+1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif i == ncols-1 and j == 0:
            if m[i][j] <= m[i][j+1] and  m[i][j] <= m[i-1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif i == ncols-1 and j == nrows-1:
            if m[i][j] <= m[i][j-1] and  m[i][j] <= m[i-1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif i == 0:
            if m[i][j] <= m[i+1][j] and  m[i][j] <= m[i][j-1] and  m[i][j] <= m[i][j+1]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif i == ncols-1:
            if m[i][j] <= m[i][j+1] and  m[i][j] <= m[i-1][j] and  m[i][j] <= m[i][j-1]:
                count += 1   
                print(f"m[{i}][{j}] = {m[i][j]}") 
        elif j == 0:
            if m[i][j] <= m[i+1][j] and  m[i][j] <= m[i-1][j] and  m[i][j] <= m[i][j+1]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        elif j == nrows-1:
            if m[i][j] <= m[i-1][j] and  m[i][j] <= m[i][j-1] and  m[i][j] <= m[i+1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
        else:
            if m[i][j] <= m[i][j+1] and  m[i][j] <= m[i+1][j] and  m[i][j] <= m[i][j-1] and  m[i][j] <= m[i-1][j]:
                count += 1
                print(f"m[{i}][{j}] = {m[i][j]}")
print(f"Кол-во локальных минимумов:{count}")

m[0][2] = 2
m[0][4] = 8
m[0][7] = 5
m[0][9] = 15
m[1][6] = 8
m[2][2] = 3
m[2][4] = 3
m[3][8] = 3
m[4][1] = 3
m[4][6] = 2
m[5][0] = 8
m[5][3] = 1
m[5][9] = 3
m[6][8] = 4
m[7][6] = 6
m[7][9] = 1
m[8][1] = 0
m[8][4] = 1
m[9][3] = 4
m[9][6] = 2
m[9][8] = 2
Кол-во локальных минимумов:21
